// <auto-generated />
using System;
using Dental.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dental.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220410202746_tables")]
    partial class tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dental.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("AppointmentID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Dental.Core.Entities.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppointmentID")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("AppointmentID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Dental.Core.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<string>("DoctorDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeTableID")
                        .HasColumnType("int");

                    b.HasKey("DoctorID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("TimeTableID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Dental.Core.Entities.TimeTable", b =>
                {
                    b.Property<int>("TimeTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("TimeTableID");

                    b.ToTable("TimeTables");
                });

            modelBuilder.Entity("Dental.Core.Entities.Client", b =>
                {
                    b.HasOne("Dental.Core.Entities.Appointment", "Appointment")
                        .WithMany("Clients")
                        .HasForeignKey("AppointmentID");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Dental.Core.Entities.Doctor", b =>
                {
                    b.HasOne("Dental.Core.Entities.Appointment", "Appointment")
                        .WithMany("Doctors")
                        .HasForeignKey("AppointmentID");

                    b.HasOne("Dental.Core.Entities.TimeTable", "TimeTable")
                        .WithMany("Doctors")
                        .HasForeignKey("TimeTableID");

                    b.Navigation("Appointment");

                    b.Navigation("TimeTable");
                });

            modelBuilder.Entity("Dental.Core.Entities.Appointment", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Dental.Core.Entities.TimeTable", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
